# Generated by Django 4.0.6 on 2022-07-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accomplishmentDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
