# Generated by Django 4.0.6 on 2022-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_accomplishmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accomplishmentDate',
            field=models.DateField(),
        ),
    ]
